### ISSUE TITLE
[Help wanted] Object grounding task - bboxes have great bias after SFT

### ISSUE THREAD

**Issue by puppyapple** [QwenLM/Qwen2.5-VL#1062]
#721 says the issue caused by transformer code has been fixed, so I install the latest commit of transformer and retrain my SFT procedure, which is a document layout analysis task. The llama-factory config is like below:
```yaml
### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 802816
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
freeze_language_model: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: docsynth300k
template: qwen2_vl
cutoff_len: 4096
max_samples: 300000
overwrite_cache: false 
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5_vl-3b/full/sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
# use_adam_mini: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 3.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# report_to: wandb

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

```
So I use a **image_max_pixels** 802816 = 1024 * 28 * 28.
In my data preparation phase, I use the **smart_resize** function to get the input weight and width to resize the bbox coordinate to the right value, the main function is like below:
```python
MIN_PIXELS = 512 * 28 * 28
MAX_PIXELS = 1024 * 28 * 28
def process_one_record(image_data, anno_string, image_save_path, mapping=CLASS_MAPPING):
    image = Image.open(io.BytesIO(image_data))
    image.save(image_save_path)
    width, height = image.size
    input_height, input_width = smart_resize(
        height, width, min_pixels=MIN_PIXELS, max_pixels=MAX_PIXELS
    )
    label_dict_list = []
    for s in anno_string:
        parts = s.strip().split()
        if len(parts) != 9:
            continue
        else:
            cls = parts[0]
            bbox_ratio = [
                float(parts[1]),
                float(parts[2]),
                float(parts[5]),
                float(parts[6]),
            ]

            # 将DocSynth300K的类别映射到DocTags类别
            if cls in mapping:
                label = mapping[cls]
            else:
                # 如果类别不在映射中，跳过此标注
                continue

            label_x1 = int(bbox_ratio[0] * input_width)
            label_y1 = int(bbox_ratio[1] * input_height)
            label_x2 = int(bbox_ratio[2] * input_width)
            label_y2 = int(bbox_ratio[3] * input_height)
            label_dict = dict(
                label=label,
                bbox_2d=[label_x1, label_y1, label_x2, label_y2],
            )
            label_dict_list.append(label_dict)

    # 将label_dict_list转换为markdown格式下的json字符串
    markdown_json = "```json\n["
    for i, item in enumerate(label_dict_list):
        if i > 0:
            markdown_json += ","
        markdown_json += "\n    " + json.dumps(item, ensure_ascii=False)
    markdown_json += "\n]\n```"

    return markdown_json
```
> the **bbox_ratio** is the original value in DocSynth300K dataset which uses the ratio of bbox width and length to the image instead of coordinate. So here I just multiply it to the resized input width and height. 
then I use these data(300k) for a full parameter SFT, after one epoch, the result still has great bias like this:

![Image](https://github.com/user-attachments/assets/7c75e350-b744-449f-a39b-11a95c3c353d)

the output of the model is below:
output:
 ```json
[
    {"label": "title", "bbox_2d": [145, 108, 963, 167]},
    {"label": "underscore", "bbox_2d": [145, 20, 963, 56]},
    {"label": "header", "bbox_2d": [146, 1, 962, 17]},
    {"label": "text", "bbox_2d": [148, 699, 1031, 1024]},
    {"label": "marginal_note", "bbox_2d": [11, 300, 56, 822]},
    {"label": "footer", "bbox_2d": [151, 183, 962, 270]},
    {"label": "section_title", "bbox_2d": [388, 274, 725, 287]},
    {"label": "page_number", "bbox_2d": [771, 1043, 788, 1055]}
]
```
input_width 616, input height 784.
I use exactly the inference code from [here](https://github.com/QwenLM/Qwen2.5-VL/blob/main/cookbooks/spatial_understanding.ipynb).
As you can see, the x and y still exceed a lot than the input_width and input_height value.

Is there any thing that I missed in my procedure? @MuyaoLi-jimo  @HumanZhong
